"""refactor

Revision ID: 6b0c9b8af9de
Revises: 23b0d3a15a64
Create Date: 2023-07-25 16:12:03.274454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c9b8af9de'
down_revision = '23b0d3a15a64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('instrument_type', sa.String(), nullable=True))
    op.drop_column('operation', 'Instrument_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('Instrument_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('operation', 'instrument_type')
    # ### end Alembic commands ###
